### ISSUE TITLE
დეტალური გვერდი:  გაკეთდეს დიზაინი (Design)

### ISSUE THREAD

**Issue by Jilberta** [GeoLabCommunity/geolab-final-project-BooksApp#9]
გასაკეთებელია დეტალური გვერდის დიზაინი თუ რა სად როდის უნდა იყოს .

**Comment by RaZma07** [comment]
![12511102_10205528338870114_1221761467_o](https://cloud.githubusercontent.com/assets/16372172/12236567/0f1cbf54-b894-11e5-931d-45bbacc41210.jpg)
![12516594_10205528338950116_1132816270_o](https://cloud.githubusercontent.com/assets/16372172/12236566/0f1c7daa-b894-11e5-9bad-46b4d6f293ee.jpg)
![12528229_10205528339070119_537896247_o](https://cloud.githubusercontent.com/assets/16372172/12236569/0f207234-b894-11e5-9410-8449543b7fd8.jpg)
![12528500_10205528339030118_1878735956_o](https://cloud.githubusercontent.com/assets/16372172/12236570/0f208cb0-b894-11e5-9cdb-43f831c9145d.jpg)
![12545817_10205528338990117_1101579455_o](https://cloud.githubusercontent.com/assets/16372172/12236568/0f1d0f36-b894-11e5-9dce-c2beb8147432.jpg)
